### ISSUE TITLE
Definir outro tema para o blog

### ISSUE THREAD

**Issue by lira92** [GDG-ToledoPR/gdg-toledopr.github.io#1]
Pessoal criamos o blog utilizando o tema default do jekyll, precisamos definir um tema mais elegante. comentem aqui suas sugestões.

**Comment by lira92** [comment]
Estes dos sites tem alguns temas para jekyll:
http://jekyllthemes.org/
http://themes.jekyllrc.org/

**Comment by grassiricardo** [comment]
Segue algumas sugestões:
http://jekyllthemes.org/themes/console/
https://jekyllthemes.io/theme/38940153/bitwiser-material
https://jekyllthemes.io/theme/49091388/sleek_blog

**Comment by lira92** [comment]
@grassiricardo gostei do console, o ultimo também é interessante que tem até uma parte que daria pra utilizar para os eventos né.

**Comment by grassiricardo** [comment]
@lira92 curti também o do console, acho que vai ficar legal!

**Comment by lucasbaccan** [comment]
@lira92 , Ele é bem minimalista achei, gostei, fácil e pratico. (https://github.com/jaehee0113/console)

**Comment by lira92** [comment]
Pessoal, mais alguma sugestão?

**Comment by lira92** [comment]
Segue mais duas sugestões:
https://hugocarreira.github.io/jekyll-vision-casper-theme/
http://projectpages.github.io/project-pages/

**Comment by roberto-filho** [comment]
**Pergunta**: dá pra mudar o tema fácilmente dps? 
* Se der podemos escolher um simples que se adequa ao que precisamos (eu voto o tema *console* tb)
* Se não der sugiro aquele *sleek_blog* que tem umas coisinhas a mais que podemos usar no futuro

**Comment by lira92** [comment]
@roberto-filho olha, não é muito difícil não além do que mão de obra não falta né? rsrsrs, mas enfim gostei do sleek_blog também pela funcionalidade que podemos adicionar para os eventos, mas mesmo que utilizemos o console, podemos criar a parte de eventos no tema. 

Bom só temos que chegar a um consenso, rsrs. 

Não fiquem presos as sugestões faça buscas e sugiram outros, só se atentem que alguns podem ser pagos, e no momento não temos tantos recursos assim.
